#!/usr/bin/python3

import json
import subprocess


def add_module_names(project, program_or_module, module_names):
    for name in program_or_module.get("modules", []):
        if name in module_names:
            continue
        module_names.append(name)
        module = project["modules"][name]
        add_module_names(project, module, module_names)


def get_modules(project, program_or_module):
    module_names = []
    add_module_names(project, program_or_module, module_names)
    modules = []
    for name in module_names:
        modules.append(project["modules"][name])
    return modules


project = json.load(open("cube.json"))
for program in project["programs"]:
    if program["name"] != "cube":
        continue

    modules = get_modules(project, program)
    libraries = set(program.get("libraries", []))
    for module in modules:
        libraries.update(module.get("libraries", []))

    command = ["gcc", "-g", "-Wall"]
    for module in modules:
        for source in module["sources"]:
            command.append(source)
        for dir in module["include-directories"]:
            command.append("-I" + dir)
    for source in program.get("sources", []):
        command.append(source)
    for name, value in program.get("defines", {}).items():
        command.append("-D" + name + "=" + value)
    for library in libraries:
        command.append("-l" + library)
    command.extend(["-o", "cube"])

    subprocess.run(command)
